language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1

gemfile:
  - gemfiles/rspec2.gemfile
  - gemfiles/rspec3.gemfile

matrix:
  allow_failures:
   - rvm: 1.9.3

notifications:
  email:
    on_success: never
